### ISSUE TITLE
Max mqtt payload size

### ISSUE THREAD

**Issue by MarcoFierimonte** [eclipse/paho.mqtt.python#107]
Hello,

Is there any limit on the message size that a Client Mqtt Paho can receive? Furthermore can this payload size depends from Operating System or programming language (java, python, etc..) ?

Thanks.
Marco

**Comment by miketran78727** [comment]
@MarcoFierimonte MQTT allows applications to send Control Packets of size up to 268,435,455 (256 MB) http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180836 

However, the limit can be imposed by the broker for practical purposes.  For example, IBM MessageSight has a concept of Endpoint (port) which allows the administrator to set maximum message size. https://www.ibm.com/support/knowledgecenter/SSCGGQ_1.2.0/com.ibm.ism.doc/Administering/ad00360_.html

**Comment by ralight** [comment]
As Mike says, this is more likely to be enforced at the server side than the client side.

**Comment by MarcoFierimonte** [comment]
@miketran78727 & @ralight thanks for your replies. I read MQTT specs but I checked different behaviour of Paho Clients on SO like: Raspbian, Windows and CentOS. On Rasbian the client Paho (Python) can't receive more than 2 KB of message payload. Instead on CentOS the maximum size is 4 KB.  It makes sense? 
In my project I implemented a MQTT broker using a library called Netty and different Paho clients communicate with it. It works well with Java Paho clients but not with Python clients, they give me the error "ERRNO 11" if payload size is big (around 2-4 KB).

Thanks.
Marco

**Comment by ralight** [comment]
I've tested this code on raspbian and it receives a 200kB message just fine. Could you test at your end?

    import paho.mqtt.client as mqtt

    def on_message(mqttc, obj, msg):
        print(msg.topic+" "+str(len(msg.payload)))

    mqttc = mqtt.Client()
    mqttc.on_message = on_message
    mqttc.connect("test.mosquitto.org", 1883, 60)
    mqttc.subscribe("size", 0)
    mqttc.loop_forever()

**Comment by MarcoFierimonte** [comment]
If you tested it and works the problem could be my Java Netty Broker. I am trying to find the bug. Thank you for your help @ralight  :)

Marco

**Comment by MarcoFierimonte** [comment]
I missed a important part @ralight . I am using the websocket protocol to communicate. Maybe this is the problem, 2KB is the client paho on websocket limit? :)

**Comment by yoch** [comment]
maybe related to #89 ?

**Comment by PierreF** [comment]
Their is some issue with large WebSockets message. I generate client disconnection with message larger than ~20kb on localhost.
I think is due to [_buffrered_read](https://github.com/eclipse/paho.mqtt.python/blob/33b7c95df3df330ab2ffb7b325e94164db1159fd/src/paho/mqtt/client.py#L2760) that seems to assume that socket.recv(wanted_size) returns data of size wanted_size, which is not always true.

I'll try to come with a PR that fix this issue

**Comment by mvsnbharath** [comment]
Is there any minimum requirement as well regarding the size of a MQTT message payload?

**Comment by PierreF** [comment]
This issue is fixed in develop branch.

**Comment by huntc** [comment]
> https://github.com/eclipse/paho.mqtt.python/issues/107#issuecomment-422845484

Because MQTT `Publish` messages and friends must encode the "remaining length" in the fixed header, the message must be held in memory during construction so that this value can be determined i.e. it isn't possible to stream a payload. Therefore, MQTT clients on resource constrained devices (which should be all computers!) should enforce a maximum payload size so that memory isn't blown. I don't know if this explains what you're seeing, but it may help.

**Comment by sujith1038** [comment]
How to read the message continuously with out data loss, 
i tried using both loop_start() and also loop_forever() , but i still have some data loss,.


currently i have a scenario where per second 10 messages are being published, but when i receive i could receive only 4 sometimes 5 , any inputs on how to overcome this challenge.
