### ISSUE TITLE
client sometimes crash because the topic can't be decoded in utf8

### ISSUE THREAD

**Issue by yoch** [eclipse/paho.mqtt.python#75]
Sometimes I got this exception (and the client hangs) : 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\yoch\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\yoch\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/yoch/Desktop/paho.mqtt/src\paho\mqtt\client.py", line 2567, in _thread_main
    self.loop_forever()
  File "C:/Users/yoch/Desktop/paho.mqtt/src\paho\mqtt\client.py", line 1367, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "C:/Users/yoch/Desktop/paho.mqtt/src\paho\mqtt\client.py", line 891, in loop
    rc = self.loop_read(max_packets)
  File "C:/Users/yoch/Desktop/paho.mqtt/src\paho\mqtt\client.py", line 1169, in loop_read
    rc = self._packet_read()
  File "C:/Users/yoch/Desktop/paho.mqtt/src\paho\mqtt\client.py", line 1754, in _packet_read
    rc = self._packet_handle()
  File "C:/Users/yoch/Desktop/paho.mqtt/src\paho\mqtt\client.py", line 2227, in _packet_handle
    return self._handle_publish()
  File "C:/Users/yoch/Desktop/paho.mqtt/src\paho\mqtt\client.py", line 2385, in _handle_publish
    message.topic = message.topic.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 20: invalid continuation byte
```

To reproduce this bug, you can simply connect a client to `"iot.eclipse.org"` and subscribe to `"#"`, usually after a short time the crash occurs.

**Comment by ralight** [comment]
Thanks, I've pushed a fix for this - the exception will now be raised when the user accesses message.topic in the on_message callback.

**Comment by yoch** [comment]
According with the specification, it should rather close the connection (the broker is buggy). But I don't know what is the best choice in practice.

> If a Server or Client receives a Control Packet containing ill-formed UTF-8 it MUST close the Network Connection [MQTT-1.5.3-1].

**Comment by andrewbernard** [comment]
This defect is still present with Python 3.5.2 and latest install from pip as at 7 June 2017. The example given crashes reliably after a few lines of output:

    client.connect("iot.eclipse.org", 1883, 60)

Error:

    File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 373, in topic
        return self._topic.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 31: invalid continuation byte

**Comment by brainstorm** [comment]
I can confirm that the example from the ["getting started" section in the readme](https://pypi.python.org/pypi/paho-mqtt/1.1#usage-and-api) breaks as well for me, running python 3.5.2 from Anaconda:

```
$SYS/broker/connection/owner-PC.bridgeConnection/state b'1'
$SYS/broker/connection/Nozomi-PC.bridgeConnection/state b'0'
$SYS/broker/connection/TANTO.bridgeConnection/state b'1'
$SYS/broker/connection/Serv.bridgeConnection/state b'1'
$SYS/broker/connection/PDVBER02.bridgeConnection/state b'1'
Traceback (most recent call last):
  File "pcgr_mqtt.py", line 27, in <module>
    client.loop_forever()
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 1838, in _packet_read
    rc = self._packet_handle()
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 2285, in _packet_handle
    return self._handle_publish()
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 2456, in _handle_publish
    self._handle_on_message(message)
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 2603, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "pcgr_mqtt.py", line 15, in on_message
    print(msg.topic+" "+str(msg.payload))
  File "/Users/romanvg/.miniconda/lib/python3.5/site-packages/paho/mqtt/client.py", line 357, in topic
    return self._topic.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 31: invalid continuation byte
```

**Comment by PierreF** [comment]
This issue is tracked under #173.

As reminder paho-mqtt 1.3.0 added the ability for the client to handle non-utf-8 topic. Within the on_message you may add a try/except to catch this UnicodeDecodeError.

**Comment by ronaulipardede** [comment]
Traceback (most recent call last):
  File "/home/pi/mqtt_try2.py", line 30, in <module>
    client.connect(Broker, 1883, 60)
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 895, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

How about to fix this error? Thank you.
